In [1]:
import numpy as np
import pandas as pd

In [2]:
dat=pd.read_csv('nifty50.csv')

In [3]:
dat

,Date,ADANIPORTS.NS,TECHM.NS,BRITANNIA.NS,TCS.NS,SUNPHARMA.NS,INFY.NS,HINDALCO.NS,DRREDDY.NS,HCLTECH.NS,...,RELIANCE.NS,SBILIFE.NS,HDFCLIFE.NS,BAJFINANCE.NS,AXISBANK.NS,HDFCBANK.NS,TATAMOTORS.NS,ICICIBANK.NS,POWERGRID.NS,INDUSINDBK.NS
0,01-01-2016,267.549988,520.049988,1493.199951,1208.199951,815.549988,552.625000,84.900002,3108.600098,422.924988,...,507.674988,NaN,NaN,609.585022,449.899994,544.375000,401.899994,239.091003,141.000000,963.849976
1,04-01-2016,257.950012,516.400024,1486.300049,1184.800049,799.099976,539.450012,80.750000,3056.000000,422.975006,...,497.649994,NaN,NaN,605.244995,438.399994,535.250000,377.049988,232.317993,140.949997,934.200012
2,05-01-2016,255.699997,521.900024,1483.349976,1174.469971,800.500000,537.025024,82.599998,3070.649902,421.399994,...,502.575012,NaN,NaN,599.784973,436.450012,531.200012,374.450012,233.363998,139.149994,935.250000
3,06-01-2016,251.800003,525.099976,1500.849976,1190.800049,791.950012,534.674988,80.550003,3046.250000,420.700012,...,516.099976,NaN,NaN,610.724976,430.700012,533.549988,365.899994,227.363998,139.500000,943.950012
4,07-01-2016,245.000000,510.799988,1473.280029,1185.619995,783.799988,525.400024,76.650002,2991.800049,412.524994,...,506.625000,NaN,NaN,610.630005,409.250000,528.099976,343.549988,224.317993,138.100006,925.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
dat.drop(['SBILIFE.NS','HDFCLIFE.NS'],axis=1,inplace=True)

In [5]:
dat.dropna(inplace=True)

In [6]:
dat

,Date,ADANIPORTS.NS,TECHM.NS,BRITANNIA.NS,TCS.NS,SUNPHARMA.NS,INFY.NS,HINDALCO.NS,DRREDDY.NS,HCLTECH.NS,...,ONGC.NS,SBIN.NS,RELIANCE.NS,BAJFINANCE.NS,AXISBANK.NS,HDFCBANK.NS,TATAMOTORS.NS,ICICIBANK.NS,POWERGRID.NS,INDUSINDBK.NS
0,01-01-2016,267.549988,520.049988,1493.199951,1208.199951,815.549988,552.625000,84.900002,3108.600098,422.924988,...,161.667007,227.800003,507.674988,609.585022,449.899994,544.375000,401.899994,239.091003,141.000000,963.849976
1,04-01-2016,257.950012,516.400024,1486.300049,1184.800049,799.099976,539.450012,80.750000,3056.000000,422.975006,...,158.699997,220.699997,497.649994,605.244995,438.399994,535.250000,377.049988,232.317993,140.949997,934.200012
2,05-01-2016,255.699997,521.900024,1483.349976,1174.469971,800.500000,537.025024,82.599998,3070.649902,421.399994,...,161.233002,217.750000,502.575012,599.784973,436.450012,531.200012,374.450012,233.363998,139.149994,935.250000
3,06-01-2016,251.800003,525.099976,1500.849976,1190.800049,791.950012,534.674988,80.550003,3046.250000,420.700012,...,158.367004,216.850006,516.099976,610.724976,430.700012,533.549988,365.899994,227.363998,139.500000,943.950012
4,07-01-2016,245.000000,510.799988,1473.280029,1185.619995,783.799988,525.400024,76.650002,2991.800049,412.524994,...,151.067001,209.550003,506.625000,610.630005,409.250000,528.099976,343.549988,224.317993,138.100006,925.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,24-12-2020,478.549988,947.250000,3618.250000,2909.350098,590.450012,1236.050049,236.949997,5201.799805,919.349976,...,93.150002,266.850006,1994.150024,5184.899902,610.200012,1397.099976,175.949997,513.549988,190.000000,852.799988
1228,28-12-2020,483.549988,947.099976,3603.550049,2929.399902,586.950012,1240.300049,239.899994,5201.799805,921.799988,...,93.800003,275.200012,2003.300049,5204.100098,617.650024,1412.849976,186.350006,520.099976,191.550003,866.950012
1229,29-12-2020,483.399994,965.650024,3593.300049,2930.500000,590.599976,1250.300049,235.600006,5165.600098,935.900024,...,93.150002,277.899994,1990.050049,5200.500000,630.200012,1427.199951,183.449997,528.799988,189.699997,912.900024
1230,30-12-2020,485.399994,983.250000,3583.899902,2909.300049,584.000000,1246.800049,237.399994,5170.950195,940.700012,...,93.250000,276.899994,1995.500000,5334.149902,625.099976,1432.500000,184.149994,528.750000,190.199997,899.049988
1231,31-12-2020,483.750000,973.200012,3576.350098,2862.750000,592.349976,1255.800049,240.550003,5205.100098,946.150024,...,93.050003,274.950012,1985.300049,5295.200195,620.450012,1436.300049,183.850006,535.049988,189.850006,894.950012

In [7]:
dat.set_index('Date',inplace=True)
dat

,ADANIPORTS.NS,TECHM.NS,BRITANNIA.NS,TCS.NS,SUNPHARMA.NS,INFY.NS,HINDALCO.NS,DRREDDY.NS,HCLTECH.NS,HINDUNILVR.NS,...,ONGC.NS,SBIN.NS,RELIANCE.NS,BAJFINANCE.NS,AXISBANK.NS,HDFCBANK.NS,TATAMOTORS.NS,ICICIBANK.NS,POWERGRID.NS,INDUSINDBK.NS
Date,,,,,,,,,,,,,,,,,,,,,
01-01-2016,267.549988,520.049988,1493.199951,1208.199951,815.549988,552.625000,84.900002,3108.600098,422.924988,856.549988,...,161.667007,227.800003,507.674988,609.585022,449.899994,544.375000,401.899994,239.091003,141.000000,963.849976
04-01-2016,257.950012,516.400024,1486.300049,1184.800049,799.099976,539.450012,80.750000,3056.000000,422.975006,859.000000,...,158.699997,220.699997,497.649994,605.244995,438.399994,535.250000,377.049988,232.317993,140.949997,934.200012
05-01-2016,255.699997,521.900024,1483.349976,1174.469971,800.500000,537.025024,82.599998,3070.649902,421.399994,847.950012,...,161.233002,217.750000,502.575012,599.784973,436.450012,531.200012,374.450012,233.363998,139.149994,935.250000
06-01-2016,251.800003,525.099976,1500.849976,1190.800049,791.950012,534.674988,80.550003,3046.250000,420.700012,843.049988,...,158.367004,216.850006,516.099976,610.724976,430.700012,533.549988,365.899994,227.363998,139.500000,943.950012
07-01-2016,245.000000,510.799988,1473.280029,1185.619995,783.799988,525.400024,76.650002,2991.800049,412.524994,820.250000,...,151.067001,209.550003,506.625000,610.630005,409.250000,528.099976,343.549988,224.317993,138.100006,925.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24-12-2020,478.549988,947.250000,3618.250000,2909.350098,590.450012,1236.050049,236.949997,5201.799805,919.349976,2402.250000,...,93.150002,266.850006,1994.150024,5184.899902,610.200012,1397.099976,175.949997,513.549988,190.000000,852.799988
28-12-2020,483.549988,947.099976,3603.550049,2929.399902,586.950012,1240.300049,239.899994,5201.799805,921.799988,2388.899902,...,93.800003,275.200012,2003.300049,5204.100098,617.650024,1412.849976,186.350006,520.099976,191.550003,866.950012
29-12-2020,483.399994,965.650024,3593.300049,2930.500000,590.599976,1250.300049,235.600006,5165.600098,935.900024,2384.300049,...,93.150002,277.899994,1990.050049,5200.500000,630.200012,1427.199951,183.449997,528.799988,189.699997,912.900024
30-12-2020,485.399994,983.250000,3583.899902,2909.300049,584.000000,1246.800049,237.399994,5170.950195,940.700012,2406.600098,...,93.250000,276.899994,1995.500000,5334.149902,625.099976,1432.500000,184.149994,528.750000,190.199997,899.049988
31-12-2020,483.750000,973.200012,3576.350098,2862.750000,592.349976,1255.800049,240.550003,5205.100098,946.150024,2395.399902,...,93.050003,274.950012,1985.300049,5295.200195,620.450012,1436.300049,183.850006,535.049988,189.850006,894.950012

In [8]:
name = list(dat)
name

['ADANIPORTS.NS',
 'TECHM.NS',
 'BRITANNIA.NS',
 'TCS.NS',
 'SUNPHARMA.NS',
 'INFY.NS',
 'HINDALCO.NS',
 'DRREDDY.NS',
 'HCLTECH.NS',
 'HINDUNILVR.NS',
 'TATASTEEL.NS',
 'NTPC.NS',
 'CIPLA.NS',
 'ITC.NS',
 'BPCL.NS',
 'WIPRO.NS',
 'JSWSTEEL.NS',
 'GAIL.NS',
 'DIVISLAB.NS',
 'ULTRACEMCO.NS',
 'NESTLEIND.NS',
 'ASIANPAINT.NS',
 'EICHERMOT.NS',
 'IOC.NS',
 'GRASIM.NS',
 'BAJAJ-AUTO.NS',
 'HDFC.NS',
 'M&M.NS',
 'UPL.NS',
 'SHREECEM.NS',
 'MARUTI.NS',
 'TITAN.NS',
 'BAJAJFINSV.NS',
 'KOTAKBANK.NS',
 'COALINDIA.NS',
 'BHARTIARTL.NS',
 'HEROMOTOCO.NS',
 'LT.NS',
 'ONGC.NS',
 'SBIN.NS',
 'RELIANCE.NS',
 'BAJFINANCE.NS',
 'AXISBANK.NS',
 'HDFCBANK.NS',
 'TATAMOTORS.NS',
 'ICICIBANK.NS',
 'POWERGRID.NS',
 'INDUSINDBK.NS']

In [9]:
df=pd.DataFrame()

In [10]:
df['Name']=name

In [11]:
def volat(ser):
    l=ser.pct_change()
    return l.std()*np.sqrt(252)

In [12]:
df['Volatility']=df['Name'].apply(lambda x:volat(dat[x]))
df

             Name  Volatility
0   ADANIPORTS.NS    0.364064
1        TECHM.NS    0.309413
2    BRITANNIA.NS    0.266172
3          TCS.NS    0.259513
4    SUNPHARMA.NS    0.330073
5         INFY.NS    0.284967
6     HINDALCO.NS    0.418163
7      DRREDDY.NS    0.292212
8      HCLTECH.NS    0.277016
9   HINDUNILVR.NS    0.235222
10   TATASTEEL.NS    0.383069
11        NTPC.NS    0.262924
12       CIPLA.NS    0.283166
13         ITC.NS    0.275474
14        BPCL.NS    0.388018
15       WIPRO.NS    0.257783
16    JSWSTEEL.NS    0.362129
17        GAIL.NS    0.337781
18    DIVISLAB.NS    0.357694
19  ULTRACEMCO.NS    0.289166
20   NESTLEIND.NS    0.251671
21  ASIANPAINT.NS    0.256538
22   EICHERMOT.NS    0.344740
23         IOC.NS    0.331741
24      GRASIM.NS    0.333541
25  BAJAJ-AUTO.NS    0.261465
26        HDFC.NS    0.298966
27         M&M.NS    0.320909
28         UPL.NS    0.370950
29    SHREECEM.NS    0.302826
30      MARUTI.NS    0.314686
31       TITAN.NS    0.341155
32  BAJAJFINSV.NS    0.367858
33   KOTAKBANK.NS    0.284107
34   COALINDIA.NS    0.293808
35  BHARTIARTL.NS    0.345828
36  HEROMOTOCO.NS    0.306199
37          LT.NS    0.289170
38        ONGC.NS    0.351874
39        SBIN.NS    0.383879
40    RELIANCE.NS    0.308033
41  BAJFINANCE.NS    0.418348
42    AXISBANK.NS    0.384495
43    HDFCBANK.NS    0.236647
44  TATAMOTORS.NS    0.481753
45   ICICIBANK.NS    0.368060
46   POWERGRID.NS    0.242771
47  INDUSINDBK.NS    0.471930

In [13]:

# for i in range(len(name)):
#     l=dat[name[i]]
#     l=l.pct_change()
#     a=l.std()*np.sqrt(252)
#     df['Volatility'][i]=a
# df

In [14]:
def CAGR(data):
    init=data[0]
    fin=data[-1]
    timep=5
    val = (fin/init)**(1/timep)
    return (val-1)*100

In [15]:
df['CAGR']=df['Name'].apply(lambda x:CAGR(dat[x]))
df

             Name  Volatility       CAGR
0   ADANIPORTS.NS    0.364064  12.575325
1        TECHM.NS    0.309413  13.352578
2    BRITANNIA.NS    0.266172  19.087016
3          TCS.NS    0.259513  18.830773
4    SUNPHARMA.NS    0.330073  -6.195093
5         INFY.NS    0.284967  17.841427
6     HINDALCO.NS    0.418163  23.157123
7      DRREDDY.NS    0.292212  10.859482
8      HCLTECH.NS    0.277016  17.473344
9   HINDUNILVR.NS    0.235222  22.835829
10   TATASTEEL.NS    0.383069  21.286880
11        NTPC.NS    0.262924  -3.773207
12       CIPLA.NS    0.283166   4.583415
13         ITC.NS    0.275474  -0.869937
14        BPCL.NS    0.388018   4.994291
15       WIPRO.NS    0.257783  13.105079
16    JSWSTEEL.NS    0.362129  30.398617
17        GAIL.NS    0.337781   3.456410
18    DIVISLAB.NS    0.357694  27.007865
19  ULTRACEMCO.NS    0.289166  13.367303
20   NESTLEIND.NS    0.251671  26.024320
21  ASIANPAINT.NS    0.256538  25.762236
22   EICHERMOT.NS    0.344740   7.817941
23         IOC.NS    0.331741  -3.433781
24      GRASIM.NS    0.333541   9.713368
25  BAJAJ-AUTO.NS    0.261465   6.463992
26        HDFC.NS    0.298966  15.248421
27         M&M.NS    0.320909   2.636708
28         UPL.NS    0.370950   9.698567
29    SHREECEM.NS    0.302826  16.100701
30      MARUTI.NS    0.314686  10.522890
31       TITAN.NS    0.341155  34.803525
32  BAJAJFINSV.NS    0.367858  35.033141
33   KOTAKBANK.NS    0.284107  22.370843
34   COALINDIA.NS    0.293808 -16.517873
35  BHARTIARTL.NS    0.345828  10.269147
36  HEROMOTOCO.NS    0.306199   2.974397
37          LT.NS    0.289170   8.420237
38        ONGC.NS    0.351874 -10.459607
39        SBIN.NS    0.383879   3.834100
40    RELIANCE.NS    0.308033  31.355444
41  BAJFINANCE.NS    0.418348  54.088284
42    AXISBANK.NS    0.384495   6.639515
43    HDFCBANK.NS    0.236647  21.414177
44  TATAMOTORS.NS    0.481753 -14.479717
45   ICICIBANK.NS    0.368060  17.480619
46   POWERGRID.NS    0.242771   6.130033
47  INDUSINDBK.NS    0.471930  -1.472408

In [16]:
df['Sharpe Ratio']=((df['CAGR']-6)/df['Volatility'])
df

             Name  Volatility       CAGR  Sharpe Ratio
0   ADANIPORTS.NS    0.364064  12.575325     18.060905
1        TECHM.NS    0.309413  13.352578     23.762983
2    BRITANNIA.NS    0.266172  19.087016     49.167536
3          TCS.NS    0.259513  18.830773     49.441825
4    SUNPHARMA.NS    0.330073  -6.195093    -36.946605
5         INFY.NS    0.284967  17.841427     41.553717
6     HINDALCO.NS    0.418163  23.157123     41.029792
7      DRREDDY.NS    0.292212  10.859482     16.630002
8      HCLTECH.NS    0.277016  17.473344     41.417642
9   HINDUNILVR.NS    0.235222  22.835829     71.574206
10   TATASTEEL.NS    0.383069  21.286880     39.906359
11        NTPC.NS    0.262924  -3.773207    -37.171173
12       CIPLA.NS    0.283166   4.583415     -5.002665
13         ITC.NS    0.275474  -0.869937    -24.938578
14        BPCL.NS    0.388018   4.994291     -2.591916
15       WIPRO.NS    0.257783  13.105079     27.562228
16    JSWSTEEL.NS    0.362129  30.398617     67.375525
17        GAIL.NS    0.337781   3.456410     -7.530294
18    DIVISLAB.NS    0.357694  27.007865     58.731463
19  ULTRACEMCO.NS    0.289166  13.367303     25.477730
20   NESTLEIND.NS    0.251671  26.024320     79.565358
21  ASIANPAINT.NS    0.256538  25.762236     77.034448
22   EICHERMOT.NS    0.344740   7.817941      5.273373
23         IOC.NS    0.331741  -3.433781    -28.437212
24      GRASIM.NS    0.333541   9.713368     11.133181
25  BAJAJ-AUTO.NS    0.261465   6.463992      1.774585
26        HDFC.NS    0.298966  15.248421     30.934703
27         M&M.NS    0.320909   2.636708    -10.480529
28         UPL.NS    0.370950   9.698567      9.970530
29    SHREECEM.NS    0.302826  16.100701     33.354761
30      MARUTI.NS    0.314686  10.522890     14.372721
31       TITAN.NS    0.341155  34.803525     84.429350
32  BAJAJFINSV.NS    0.367858  35.033141     78.924920
33   KOTAKBANK.NS    0.284107  22.370843     57.622069
34   COALINDIA.NS    0.293808 -16.517873    -76.641433
35  BHARTIARTL.NS    0.345828  10.269147     12.344714
36  HEROMOTOCO.NS    0.306199   2.974397     -9.881171
37          LT.NS    0.289170   8.420237      8.369592
38        ONGC.NS    0.351874 -10.459607    -46.776939
39        SBIN.NS    0.383879   3.834100     -5.642135
40    RELIANCE.NS    0.308033  31.355444     82.314042
41  BAJFINANCE.NS    0.418348  54.088284    114.948081
42    AXISBANK.NS    0.384495   6.639515      1.663261
43    HDFCBANK.NS    0.236647  21.414177     65.135612
44  TATAMOTORS.NS    0.481753 -14.479717    -42.510846
45   ICICIBANK.NS    0.368060  17.480619     31.192259
46   POWERGRID.NS    0.242771   6.130033      0.535622
47  INDUSINDBK.NS    0.471930  -1.472408    -15.833720

In [17]:
df.sort_values('Sharpe Ratio',ascending=False).head(15)

             Name  Volatility       CAGR  Sharpe Ratio
41  BAJFINANCE.NS    0.418348  54.088284    114.948081
31       TITAN.NS    0.341155  34.803525     84.429350
40    RELIANCE.NS    0.308033  31.355444     82.314042
20   NESTLEIND.NS    0.251671  26.024320     79.565358
32  BAJAJFINSV.NS    0.367858  35.033141     78.924920
21  ASIANPAINT.NS    0.256538  25.762236     77.034448
9   HINDUNILVR.NS    0.235222  22.835829     71.574206
16    JSWSTEEL.NS    0.362129  30.398617     67.375525
43    HDFCBANK.NS    0.236647  21.414177     65.135612
18    DIVISLAB.NS    0.357694  27.007865     58.731463
33   KOTAKBANK.NS    0.284107  22.370843     57.622069
3          TCS.NS    0.259513  18.830773     49.441825
2    BRITANNIA.NS    0.266172  19.087016     49.167536
5         INFY.NS    0.284967  17.841427     41.553717
8      HCLTECH.NS    0.277016  17.473344     41.417642